export default [
    { id: 1, pingoCoupleQUestion: 'What three qualities do you value most in a partner?' },
    { id: 2, pingoCoupleQUestion: 'How do you envision our future together in 5 years?' },
    { id: 3, pingoCoupleQUestion: 'What is your favorite shared memory?' },
    { id: 4, pingoCoupleQUestion: "How do you feel when I'm around?" },
    { id: 5, pingoCoupleQUestion: 'What is your favorite color and why?' },
    { id: 6, pingoCoupleQUestion: 'What do you want to achieve together in the next 10 years?' },
    { id: 7, pingoCoupleQUestion: 'If you could change one thing about our relationship, what would it be?' },
    { id: 8, pingoCoupleQUestion: 'What are your best childhood memories?' },
    { id: 9, pingoCoupleQUestion: 'What makes you happy in your relationship?' },
    { id: 10, pingoCoupleQUestion: 'What movie or book reminds you of us?' },
    { id: 11, pingoCoupleQUestion: 'What three words describe your ideal date?' },
    { id: 12, pingoCoupleQUestion: 'How do you unwind after a hard day?' },
    { id: 13, pingoCoupleQUestion: 'What is more important to you: support or freedom?' },
    { id: 14, pingoCoupleQUestion: 'How do you want me to support you in difficult times?' },
    { id: 15, pingoCoupleQUestion: 'What are your favorite traditions that we could create together?' },
    { id: 16, pingoCoupleQUestion: 'What would be your ideal vacation together?' },
    { id: 17, pingoCoupleQUestion: 'If we could go anywhere right now, where would we go?' },
    { id: 18, pingoCoupleQUestion: 'What is your favorite song that reminds you of us?' },
    { id: 19, pingoCoupleQUestion: "How do you feel when we're not together?" },
    { id: 20, pingoCoupleQUestion: 'What do you find most romantic about a relationship?' },
    { id: 21, pingoCoupleQUestion: "How do you react when I'm sad?" },
    { id: 22, pingoCoupleQUestion: 'If you could spend the whole day with me, what would we do?' },
    { id: 23, pingoCoupleQUestion: 'What is the most important thing to you in a long-term relationship?' },
    { id: 24, pingoCoupleQUestion: 'What is your favorite thing to do on the weekend?' },
    { id: 25, pingoCoupleQUestion: 'What was the best advice you received in a relationship?' },
    { id: 26, pingoCoupleQUestion: 'What attracted you most to me?' },
    { id: 27, pingoCoupleQUestion: 'How do you imagine your ideal holiday with your partner?' },
    { id: 28, pingoCoupleQUestion: 'What do you want to change most about your daily routine?' },
    { id: 29, pingoCoupleQUestion: 'How do you like to celebrate important moments in life?' },
    { id: 30, pingoCoupleQUestion: 'What are your strongest feelings for me?' },
    { id: 31, pingoCoupleQUestion: 'What are your most important concerns in a relationship?' },
    { id: 32, pingoCoupleQUestion: 'If we could take up a new hobby together, what would it be?' },
    { id: 33, pingoCoupleQUestion: 'What song could we sing together at karaoke?' },
    { id: 34, pingoCoupleQUestion: 'If you had to choose to do something together or separately, what would you choose?' },
    { id: 35, pingoCoupleQUestion: 'What is your favorite activity that you want to share with me?' },
    { id: 36, pingoCoupleQUestion: 'What are your favorite traditions together?' },
    { id: 37, pingoCoupleQUestion: 'How do you want me to celebrate your achievements?' },
    { id: 38, pingoCoupleQUestion: 'What does "mutual support" mean to you in a relationship?' },
    { id: 39, pingoCoupleQUestion: 'What is your favorite color, and why do you like it?' },
    { id: 40, pingoCoupleQUestion: 'If we could change one thing in the world together, what would it be?' },
    { id: 41, pingoCoupleQUestion: 'What is your best advice for improving your relationship?' },
    { id: 42, pingoCoupleQUestion: 'How do you feel when we cook or clean together?' },
    { id: 43, pingoCoupleQUestion: 'If you could choose one thing to change in our relationship, what would it be?' },
    { id: 44, pingoCoupleQUestion: 'If you could see us in the future, what would you like to see?' },
    { id: 45, pingoCoupleQUestion: 'If I could do one unexpected kindness for you, what would it be?' },
    { id: 46, pingoCoupleQUestion: 'What role does romance play in your relationship?' },
    { id: 47, pingoCoupleQUestion: 'If you could have a day just for yourself, what would you do?' },
    { id: 48, pingoCoupleQUestion: 'What are three things I do that make you happy?' },
    { id: 49, pingoCoupleQUestion: 'How do you like me to express my feelings for you?' },
    { id: 50, pingoCoupleQUestion: 'What is most important to you in maintaining an emotional connection?' },
];