export default [
    { id: 1, pingoCoupleDesireText: 'Tell me a few words about your significant other.' },
    { id: 2, pingoCoupleDesireText: 'Tell me about your favorite moment together.' },
    { id: 3, pingoCoupleDesireText: 'Share your best memory together.' },
    { id: 4, pingoCoupleDesireText: 'Describe the perfect date for the two of you.' },
    { id: 5, pingoCoupleDesireText: 'Tell me about what you like most about your partner.' },
    { id: 6, pingoCoupleDesireText: 'Tell me why you chose this person for yourself.' },
    { id: 7, pingoCoupleDesireText: 'Tell me how you usually celebrate important events.' },
    { id: 8, pingoCoupleDesireText: 'Sing a few lines from a song you sing together.' },
    { id: 9, pingoCoupleDesireText: 'Share your best advice for maintaining harmony in your relationship.' },
    { id: 10, pingoCoupleDesireText: 'Send one sweet message to your partner right now.' },
    { id: 11, pingoCoupleDesireText: 'Describe one thing you both want to do together in the future.' },
    { id: 12, pingoCoupleDesireText: 'Tell me what your first impression of your partner was.' },
    { id: 13, pingoCoupleDesireText: 'Share what you feel most comfortable doing when you spend time together.' },
    { id: 14, pingoCoupleDesireText: 'Tell me about the funniest moment that has ever happened to you.' },
    { id: 15, pingoCoupleDesireText: 'If you could go somewhere together, where would you go?' },
    { id: 16, pingoCoupleDesireText: 'Name three things you appreciate most about your significant other.' },
    { id: 17, pingoCoupleDesireText: 'Tell us about your first date with your partner.' },
    { id: 18, pingoCoupleDesireText: 'Share what would make you happy the next time you meet.' },
    { id: 19, pingoCoupleDesireText: 'Describe your partner’s favorite character trait.' },
    { id: 20, pingoCoupleDesireText: 'Tell us why you love spending time together.' },
];